package com.example.projetobd.entity;

public enum Genre {
    AÇÃO, COMÉDIA, COMÉDIA_ROMÂNTICA, TERROR, AVENTURA, DRAMA, FICÇÃO_CIENTÍFICA, SUSPENSE, MUSICAL, DOCUMENTÁRIO,
    ANIMAÇÃO, INFANTIL, ROMANCE, FANTASIA, GUERRA, FAROESTE, POLICIAL, BIOGRAFIA, HISTÓRICO, ESPIONAGEM, WESTERN,
    MISTÉRIO, THRILLER, CRIME, ANIME, DESCONHECIDO
}
